### ISSUE TITLE
Посмотреть видео про переменные в js из 11 часового курса

### ISSUE THREAD

**Issue by RasKerGG** [RasKerGG/SocialNetwork#8]

**Comment by Fenz1t** [comment]
Ссылка на курс:  https://www.youtube.com/watch?v=CxgOKJh4zWE
Тайминг видео: 41:24

- Переменная это именованная  ячейка памяти в которой мы храним значения, переменные дают возможность повторного доступа к переменным. 
- Имя переменной дается по разным стилям таким как: PascalCase,camelCase, а также через нижнее подчеркивание: DB_PASSWORD. PascalCase нужен для наименования типов и классов, через нижнее подчеркивание для значений,  уже известны до запуска приложения и не меняются,camelCase для всех остальных.
- Объявление переменных происходит с помощью var или let и const, а можно вообще ничего не указывать и сразу начинать с названия переменной, var является старым объявлением переменной и отличается от let только областью видимости, const является константой если мы один присваиваем значение то не сможем в следующий раз изменить. let и const появились в ECMAScript 6.
